project:
  type: website

website:
  title: "Kristen McDaniel"
  
  navbar:
    background: "#180A74"
    foreground: "white"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: CV.qmd
        text: CV
      - href: Contact.qmd
        text: Contact
    
    right: 
    - icon: github
      text: GitHub
      href: https://github.com/krismc113#
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/kristen-mcdaniel-938a99227/
      

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual